# --- !Ups

create table "WORKFLOW" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "NUMBER_OF_STEPS" int not null
);

# --- !Downs

drop table "WORKFLOW" if exists;