# --- !Ups

create table "WORKFLOW_EXECUTION" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "WORKFLOW_ID" bigint not null,
  "CURRENT_STEPS" int not null,
  "CREATION_DATE" timestamp not null default current_timestamp
);

# --- !Downs

drop table "WORKFLOW_EXECUTION" if exists;